# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JXPlaygroundDemo' do
  pod 'ReactiveObjC', '~> 3.0.0'
  pod 'AMap3DMap' #3D地图SDK #pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤用)
  pod 'AMapSearch' #搜索功能
  pod 'SDWebImage', '~> 4.0.0'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
  pod 'Masonry', '~> 1.0.2'
  pod 'ZFPlayer'
  pod 'WebViewJavascriptBridge'
  pod 'SDCycleScrollView', '~> 1.66'
  pod 'Masonry', '~> 1.0.2'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'DOPDropDownMenu-Enhanced', '~> 1.0.0'#下拉选择菜单
  pod 'WechatOpenSDK' #微信
#  pod 'AliPay', '~> 2.1.2' #支付宝
  pod 'MBProgressHUD', '~> 1.0.0'

end
