# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JXPlaygroundDemo' do
  pod 'ReactiveObjC', '~> 3.0.0'
  pod 'AMap3DMap' #3D地图SDK #pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤用)
  pod 'AMapSearch' #搜索功能
  pod 'SDWebImage', '~> 4.0.0'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
  pod 'Masonry', '~> 1.0.2'
  pod 'ZFPlayer'
  pod 'WebViewJavascriptBridge'
  pod 'SDCycleScrollView', '~> 1.66'
  pod 'Masonry', '~> 1.0.2'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'DOPDropDownMenu-Enhanced', '~> 1.0.0'#下拉选择菜单
  pod 'WechatOpenSDK' #微信
#  pod 'AliPay', '~> 2.1.2' #支付宝
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'CYLTabBarController', '~> 1.10.0'#最低只需传两个数组即可完成主流App框架搭建
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'LBXScan', '~> 2.2' #iOS 二维码、条形码
  pod 'LazyScroll' #iOS高性能异构滚动视图构建方案
  #pod 'M13ProgressSuite', '~> 1.2.9' #一个套件包含许多工具来显示iOS上的进度信息
  pod 'JDStatusBarNotification', '~> 1.5.5' #可定制的通知显示在状态栏的顶部
  pod 'TLYShyNavBar', '~> 1.1.1' #导航条
  pod 'CNPPopupController', '~> 0.3.3'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'XHWebImageAutoSize', '~> 1.0.2' #网络图片尺寸/高度自适应 - 支持异步缓存imageSize , 支持动态刷新界面
  pod 'pop', '~> 1.0.9'
end
